"""Force the desk workspaces and sidebars to re-sync from their app JSON (v1.386.0).

The same importer staleness check that stranded the Training workspace's extra
cards for five weeks (`resync_training_workspace`, v1.379.0) applies to every
record this release touches. Worth restating, because the rule is not the one most
people assume and it goes **two opposite ways**:

* a **DocType** JSON is **hash-gated** — `import_file.py` has an explicit
  `doc["doctype"] != "DocType"` escape on the age check — so editing the file at
  all re-imports it, no `modified` bump needed;
* **everything else importable**, `Workspace` and `Workspace Sidebar` included, is
  **timestamp-gated**: the file must read *newer* than the stored row, or the
  import is skipped in silence.

Both stamps here are bumped, which is enough on a site whose rows are older. This
patch is the belt to that suspenders: `reload_doc(..., force=True)` re-reads the
file and rebuilds the row regardless of the age check, which is what makes the fix
land on a row that has somehow been touched more recently than the file.

Three records:

* the **Training** workspace, which gains "Record a session";
* the new **HR** workspace, which has no row yet on any site — force is a no-op
  for it and it is listed for uniformity rather than necessity;
* the **HR sidebar**, which has to replace an orphaned `standard = 0` row sitting
  on prod since 2026-02-08 that points at a workspace which does not exist.

Not the **Training sidebar**, deliberately, even though prod carries a one-item
stub of the same vintage: this repo ships no file for it, so there is nothing to
reload and listing it would log an error on every migrate for ever. That stub is
generated by `setup/desktop_icons.py::_create_tile`, which is where it should be
fixed if it ever matters.

Deliberately overwrites the desk copy of each. These are app-owned records and the
repo is the source of truth for them; where somebody has arranged their own
workspace, that lives in a *private* Workspace, which this does not touch.
"""

import frappe

WORKSPACES = (
	("training", "training"),
	("hr_enhancements", "hr"),
)

SIDEBARS = ("hr",)


def execute():
	for module, name in WORKSPACES:
		try:
			frappe.reload_doc(module, "workspace", name, force=True)
		except Exception:
			# A workspace that will not import must not abort a migrate: the deploy
			# carries schema changes that matter more than a desk page's layout.
			frappe.log_error(
				f"Could not re-sync the {name} workspace\n{frappe.get_traceback()}",
				"Workspace sync",
			)

	for name in SIDEBARS:
		try:
			# NOT reload_doc. Its first argument is a MODULE, and it resolves the
			# path as `get_module_path(module)/<dt>/<dn>/<dn>.json`. Two things break
			# there: "erpnext_enhancements" is an app, not one of the 32 names in
			# modules.txt, so `get_module_app` throws DoesNotExistError; and even if
			# it resolved, app-level workspace_sidebar JSONs are FLAT files
			# (`<app>/workspace_sidebar/hr.json`), not `<module>/.../hr/hr.json`.
			# The except below swallowed it, so this patch's stated safety net had
			# never existed. Found by the migrate-safety audit.
			#
			# `import_file_by_path` is what `frappe/model/sync.py` itself calls for
			# these, so this is the same code path, just addressed correctly.
			from frappe.modules.import_file import import_file_by_path

			import_file_by_path(
				frappe.get_app_path("erpnext_enhancements", "workspace_sidebar", f"{name}.json"),
				force=True,
			)
		except Exception:
			frappe.log_error(
				f"Could not re-sync the {name} sidebar\n{frappe.get_traceback()}",
				"Workspace sync",
			)
