#%{ if provision_spot_vm_lb_backend }
${spot_lb_name}:
  protocol: "HTTPS"
  use_classic_version: false
  urlmap_config:
    description: "Spot VM load balancer"
    default_service: "spot-vm-backend"
  backend_service_configs:
    spot-vm-backend:
      backends:
        - backend: "${spot_vm_neg_name}"
      health_checks: ["$$mig_health_check_id"]
      protocol: "HTTP"
      port_name: "http"
  backend_buckets_config: {}
  forwarding_rules_config:
    https-rule:
      address: "$$addresses:global:${spot_glb_ip_name}"
      ssl_certificates:
        certificate_map: "$$ssl_certificates:${ssl_map_name}"
  health_check_configs: {}
#%{ endif }
#%{ if provision_standard_vm_lb_backend }
${production_lb_name}:
  protocol: "HTTPS"
  use_classic_version: false
  urlmap_config:
    description: "Production VM load balancer"
    default_service: "production-vm-backend"
  backend_service_configs:
    production-vm-backend:
      backends:
        - backend: "${standalone_vm_neg_name}"
      health_checks: ["$$mig_health_check_id"]
      port_name: "http"
  backend_buckets_config: {}
  forwarding_rules_config:
    https-rule:
      address: "$$addresses:global:${glb_ip_name}"
      ssl_certificates:
        certificate_map: "$$ssl_certificates:${ssl_map_name}"
  health_check_configs: {}
#%{ endif }
