# Copyright (c) 2026, Sapphire Fountains and contributors
# For license information, please see license.txt

"""Idempotent custom-field provisioning for the Product Configurator.

Registered in ``after_migrate`` (hooks.py). Adds the provenance field the
generation engine stamps on configured-product Items: it marks an Item as
configurator-owned so a regenerate can safely reuse it, and a hand-made Item
with a colliding code is never touched. Insert-only, mirroring
``device_management.setup``.
"""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def create_configurator_item_fields():
	"""``after_migrate`` entry point: Item provenance link."""
	if not frappe.db.exists("DocType", "Item"):
		return
	meta = frappe.get_meta("Item")
	if meta.has_field("custom_source_configuration"):
		return
	create_custom_fields(
		{
			"Item": [
				{
					"fieldname": "custom_source_configuration",
					"label": "Source Configuration",
					"fieldtype": "Link",
					"options": "Product Configuration",
					"insert_after": "description",
					"read_only": 1,
					"hidden": 1,
					"no_copy": 1,
					"description": "Set when this Item was generated by the Product Configurator.",
				}
			]
		},
		update=True,
	)
