# Copyright (c) 2026, Sapphire Fountains and contributors
# For license information, please see license.txt

"""Staging row for the Drive Link Manager dashboard
(``google_drive.drive_link_manager``).

One row per unlinked Project / Customer / Opportunity proposed for linking to an
existing Google Drive folder: the fuzzy-ranked suggestion + alternatives, the
reviewer's ``decision``, and the processing ``status``. Rows are generated by the
``scan_drive_links`` action (which clears any non-``Linked`` rows first) and
consumed by ``apply_links``; the doctype itself holds no logic — the dashboard
and its whitelisted API own the workflow."""

from frappe.model.document import Document


class DriveLinkCandidate(Document):
	pass
