#!/usr/bin/env python3
"""Regenerate ``erpnext_enhancements/tests/data/desk_icon_names.txt``: every icon name the desk can draw.

Dev-only. ``tests/test_desk_icon_names.py`` reads the file so CI, which has no frappe checkout,
can still refuse an icon name no sprite has. **Re-run it whenever production moves to a new
frappe or ERPNext release**, with the tag prod now runs, and commit the result: the file is
only as true as the release it was read from. 16.50's lucide upgrade renamed ``book-marked``,
and the old file would have kept allowing it.

``frappe.utils.icon(name)`` draws ``<svg><use href="#icon-<name>">`` (``#<name>`` for an
Espresso ``es-*`` name) into the sprites each app lists in its ``app_include_icons`` hook. A name
no sprite has draws nothing, with no error anywhere. So the names are read from exactly those
sprites, at the given tags, out of the sibling ``frappe`` and ``erpnext`` checkouts through
``git show`` rather than their working trees, which are on ``develop`` (see CLAUDE.md).

Usage, from the repo root::

  python scripts/list_desk_icon_names.py --ref v16.50.0
  python scripts/list_desk_icon_names.py --ref v16.50.0 --erpnext-ref v16.50.0 --check
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "erpnext_enhancements" / "tests" / "data" / "desk_icon_names.txt"

HOOK_RE = re.compile(r"^app_include_icons\s*=\s*\[(.*?)\]", re.S | re.M)
ASSET_RE = re.compile(r'"/assets/([a-z_]+)/([^"]+\.svg)"')
SYMBOL_RE = re.compile(r'<symbol\b[^>]*\bid="([^"]+)"')


def find_checkout(name, explicit):
	if explicit:
		return pathlib.Path(explicit).resolve()
	for ancestor in [REPO, *REPO.parents]:
		if (ancestor / name / ".git").exists():
			return ancestor / name
	sys.exit(f"could not find a sibling `{name}` checkout; pass --{name} PATH")


def show(checkout, ref, path):
	proc = subprocess.run(
		["git", "-C", str(checkout), "show", f"{ref}:{path}"],
		capture_output=True,
		text=True,
		encoding="utf-8",
	)
	if proc.returncode:
		sys.exit(f"could not read {ref}:{path} from {checkout} (fetch the tag first)\n{proc.stderr.strip()}")
	return proc.stdout


def names_for(app, checkout, ref):
	hooks = HOOK_RE.search(show(checkout, ref, f"{app}/hooks.py"))
	if not hooks:
		sys.exit(f"{app} {ref}: no app_include_icons in hooks.py")
	names = set()
	for asset_app, path in ASSET_RE.findall(hooks.group(1)):
		assert asset_app == app, (app, asset_app)
		for symbol in SYMBOL_RE.findall(show(checkout, ref, f"{app}/public/{path}")):
			# frappe.utils.icon prefixes "icon-" to everything that is not an es- name, so a
			# symbol with neither prefix (alphabets.svg's letters) is unreachable by name.
			if symbol.startswith("es-"):
				names.add(symbol)
			elif symbol.startswith("icon-"):
				names.add(symbol[len("icon-") :])
	return names


def render(frappe_ref, erpnext_ref, names):
	header = [
		"# Every icon name frappe.utils.icon() can draw on the desk, one per line.",
		f"# frappe {frappe_ref} + erpnext {erpnext_ref}, from the sprites in their app_include_icons.",
		"# Generated by scripts/list_desk_icon_names.py; regenerate it when prod moves to a new",
		"# frappe or ERPNext release. Read by tests/test_desk_icon_names.py.",
	]
	return "\n".join(header + sorted(names)) + "\n"


def main():
	parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
	parser.add_argument("--ref", required=True, help="the frappe tag production runs, e.g. v16.50.0")
	parser.add_argument("--erpnext-ref", help="the ERPNext tag (default: the same as --ref)")
	parser.add_argument("--frappe")
	parser.add_argument("--erpnext")
	parser.add_argument("--check", action="store_true", help="fail if the committed file differs")
	args = parser.parse_args()

	erpnext_ref = args.erpnext_ref or args.ref
	names = names_for("frappe", find_checkout("frappe", args.frappe), args.ref)
	names |= names_for("erpnext", find_checkout("erpnext", args.erpnext), erpnext_ref)
	text = render(args.ref, erpnext_ref, names)

	if args.check:
		if OUT.read_text(encoding="utf-8") != text:
			sys.exit(f"{OUT.relative_to(REPO)} is not what {args.ref} / {erpnext_ref} ship; regenerate it")
		print(f"{OUT.relative_to(REPO)} matches ({len(names)} names)")
		return
	OUT.write_text(text, encoding="utf-8", newline="\n")
	print(f"wrote {OUT.relative_to(REPO)} ({len(names)} names)")


if __name__ == "__main__":
	main()
